version: "3.8"
services:
  postgres-dev:
    image: postgres:alpine3.14
    container_name: postgres-dev
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=thinkmd-config"
      - EXTRA_CONF=log_statement=all\nlog_directory='pg_log'\nlog_filename='postgresql-%Y-%m-%d_%H%M%S.log'\nlogging_collector=on\nlog_min_error_statement=error
    ports:
      - "5432:5432"