version: "3.8"
services:
  postgres:
    image: postgres:alpine3.14
    container_name: postgres
    networks:
      - github_actions
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=thinkmd-config"
      - EXTRA_CONF=log_statement=all\nlog_directory='pg_log'\nlog_filename='postgresql-%Y-%m-%d_%H%M%S.log'\nlogging_collector=on\nlog_min_error_statement=error
    ports:
      - "5432:5432"
  thinkmdv5-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thinkmdv5api
    networks:
      - github_actions
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - "POSTGRES_URI=host=postgres user=admin password=admin dbname=thinkmd-config port=5432 sslmode=disable TimeZone=America/New_York"
      - "ENVIRONMENT=dev"
    volumes:
      - ./:/app

networks:
  github_actions:
    driver: bridge
