name: Generate build number

on: push

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get date
        run: |
          echo "current_date=${GITHUB_REF##*/}.${{ env.GITHUB_RUN_ID }}.${{ env.GITHUB_RUN_NUMBER }}" >> $GITHUB_ENV

      - name: Echo env date
        run: |
          echo "${{ env.current_date }}"
