name: Generate build number

on: push

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print new build number
        run: echo "Build number $GITHUB_RUN_ID $GITHUB_RUN_NUMBER"