on: push
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.1"

      - name: Build the postgres database for unit testing
        run: docker-compose -f dev.docker-compose.postgresonly.yml up -d

      - name: Setup GO testing tools
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run Static Check (GO Linter)
        run: staticcheck .

      - name: Run the unit tests
        run: go test ./... -v

      - name: Teardown unit test environment
        run: docker-compose -f dev.docker-compose.postgresonly.yml down

      - name: Build the production build for integration test
        run: docker-compose -f prod.docker-compose.yml up -d

      - name: Run the integration test
        run: echo THIS IS WHERE WE INJECT THE INTEGRATION TEST LIBRARY OR PROGRAM

      - name: Teardown integration test environment
        run: docker-compose -f prod.docker-compose.yml down
