name: Generate build number

on: push

env:
  REF: ${github.ref##*/}
  BUILD_VERSION: ${{ format('{0}.{1}.{2}', $REF, $GITHUB_RUN_ID, $GITHUB_RUN_NUMBER) }}

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get build number
        run: echo "${{ env.BUILD_VERSION }}"
