name: Generate build number

on: push

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate build number
        uses: einaregilsson/build-number@v3
              
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER $GITHUB_RUN_ID $GITHUB_RUN_NUMBER"