name: Generate build number

on: push

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: set new build number
        env:
          REF: ${github.ref##*/}
          BUILD_VERSION: ${{ format('{0}.{1}.{2}', env.REF, env.GITHUB_RUN_ID, env.GITHUB_RUN_NUMBER) }}
        run: echo $BUILD_VERSION
