name: Build and Deploy to GCP on Release

on:
  release:
    types: [created]

env:
  SERVICE_NAME: thinkmd-v5-api
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GIT_SHA: ${{ github.sha }}
  REGISTRY_REGION: northamerica-northeast1-docker.pkg.dev
  REGISTRY_ID: thinkmd-v5-dev

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to Cloud
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - uses: actions/checkout@master

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud --quiet auth configure-docker ${{ env.REGISTRY_REGION }}

      - name: Build and Push Container
        run: |-
          docker build -t ${{ env.REGISTRY_REGION }}/${{ env.PROJECT_ID }}/${{ env.REGISTRY_ID }}/${{ env.SERVICE_NAME }}:${GITHUB_REF##*/} .
          docker push ${{ env.REGISTRY_REGION }}/${{ env.PROJECT_ID }}/${{ env.REGISTRY_ID }}/${{ env.SERVICE_NAME }}:${GITHUB_REF##*/}